
version: '2'

services:
  web:
    build: .
    ports:
      - 80:80
    volumes:
      - /home/kron/Documents/projects/highloadcup.ru/data:/tmp/data:ro
      - /home/kron/Documents/projects/hlcupdocs/data/TRAIN/data:/tmp/data_unpack:ro
      - /home/kron/Documents/projects/highloadcup.ru/root/opt:/tmp/opt

